[tool.poetry]
name = "landslide4sense"
version = "0.0.1"
description = "Detecting landslide with AI"
authors = ["sebastiangarciaacosta <segaracos@outlook.com>"]

[tool.poetry.dependencies]
pip = "22.0.4"
python = ">=3.8,<3.11"
pandas = "^1.4.2"
matplotlib = "^3.5.1"
numpy = "^1.21.5"
scipy = "^1.8.0"
PyYAML = "5.1"
wandb = "^0.12.11"
torch = "1.10.0"
h5py = 3.1.0

[tool.poetry.dev-dependencies]
ipykernel = "^6.12.1"
jupyter = "^1.0.0"
pip-tools = "^6.6.0"
google-api-python-client = "^2.43.0"
google-cloud-storage = "^2.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
