data:
  dir: ${hydra:runtime.cwd}/data/
  train_list: ${hydra:runtime.cwd}/data/train_split_train.txt
  eval_lists_paths:
    - ${hydra:runtime.cwd}/data/train_split_train.txt
    - ${hydra:runtime.cwd}/data/train_split_val.txt
  eval_names:
    - train
    - val
  test_list: ${hydra:runtime.cwd}/data/valid.txt
  input_size: [128, 128]
  augmentation:
    module: landslide4sense.data.augmentations
    name: transforms

model:
  module: landslide4sense.models
  name: Unet
  args:
    n_classes: 2

optimizer:
  module: torch.optim
  name: SGD
  args:
    lr: 0.01
    weight_decay: 5e-4
    momentum: 0.9

loss:
  module: torch.nn
  name: CrossEntropyLoss
  args:
    ignore_index: 255

train:
  start_epoch: 0
  steps_per_epoch: 34
  batch_size: 100
  num_workers: 2
  num_steps: 10000
  num_steps_stop: 10000
  gpu_id: 0
  snapshot_dir: /content/drive/MyDrive/data_science_projects/landslide4sense-2022/models
  seed: 42
  callbacks:
    early_stopping:
      monitor: val_f1
      mode: max
      patience: 5
      best_result: 0.5
    wandb:
      group: Unet
      tags:
        - val_split
        - spatial_data_aug
        - sgd_momentum
        - non_spatial_data_aug
