data:
  dir: ${hydra:runtime.cwd}/data/
  train_list: ${hydra:runtime.cwd}/data/train_split_train.txt
  eval_lists_paths:
    - ${hydra:runtime.cwd}/data/train_split_train.txt
    - ${hydra:runtime.cwd}/data/train_split_val.txt
  eval_names:
    - train
    - val
  test_list: ${hydra:runtime.cwd}/data/valid.txt
  augmentation:
    module: albumentations
    transforms:
      - name: HorizontalFlip
        args:
          p: 0.5
      - name: VerticalFlip
        args: 
          p: 0.5
      - name: RandomRotate90
        args: 
          p: 0.5
      - name: Transpose
        args:
          p: 0.5 
      - name: RandomSizedCrop
        args:
          min_max_height: [96, 96]
          height: 128 
          width: 128 
          p: 0.5
      - name: ShiftScaleRotate
        args:
          p: 0.5

model:
  input_size: 128,128
  num_classes: 2
  module: landslide4sense.models
  name: Unet

train:
  start_epoch: 14
  steps_per_epoch: 34
  batch_size: 100
  num_workers: 2
  learning_rate: 1e-3
  num_steps: 10000
  num_steps_stop: 10000
  weight_decay: 5e-4
  gpu_id: 0
  snapshot_dir: ${hydra:runtime.cwd}/submissions/ 
  seed: 42
  callbacks:
    early_stopping:
      monitor: val_f1
      mode: max
      patience: 5
      best_result: 0.5
    wandb:
      name: split_data_aug_continuation_sgd
      tags:
        - val_split
        - spatial_data_aug
        - sgd_momentum
