data:
  dir: ./data/
  train_list: ./data/train.txt
  test_list: ./data/valid.txt

model:
  input_size: 128,128
  num_classes: 2
  module: landslide4sense.models
  name: Unet

train:
  batch_size: 64
  num_workers: 2
  learning_rate: 1e-3
  num_steps: 5000
  num_steps_stop: 5000
  weight_decay: 5e-4
  gpu_id: 0
  snapshot_dir: ./exp/
  restore_from: ""
  seed: 42
