data:
  dir: ${hydra:runtime.cwd}/data/
  train_list: ${hydra:runtime.cwd}/data/train_split_train.txt
  eval_lists_paths:
    - ${hydra:runtime.cwd}/data/train_split_train.txt
    - ${hydra:runtime.cwd}/data/train_split_val.txt
  eval_names:
    - train
    - val
  test_list: ${hydra:runtime.cwd}/data/valid.txt

model:
  input_size: 128,128
  num_classes: 2
  module: landslide4sense.models
  name: Unet

train:
  run_name: baseline_split
  tags:
    - val_split
  early_stopping:
    monitor: val_f1
    mode: max
    patience: 3
    best_result: 0.5
  steps_per_epoch: 200
  batch_size: 96
  num_workers: 2
  learning_rate: 1e-3
  num_steps: 10000
  num_steps_stop: 10000
  weight_decay: 5e-4
  gpu_id: 0
  snapshot_dir: ./exp/
  restore_from: ""
  seed: 42
