data:
  dir: ${hydra:runtime.cwd}/data/
  train_list: ${hydra:runtime.cwd}/data/train_split_train.txt
  eval_lists_paths:
    - ${hydra:runtime.cwd}/data/train_split_train.txt
    - ${hydra:runtime.cwd}/data/train_split_val.txt
  eval_names:
    - train
    - val
  test_list: ${hydra:runtime.cwd}/data/valid.txt
  input_size: [128, 128]
  augmentation:
    module: landslide4sense.data.augmentations
    name: transforms

model:
  restore_from: /content/drive/MyDrive/data_science_projects/landslide4sense-2022/models/misunderstood-sound-36-continuation/eager-lion-37/epoch_13_val_f1=74.757/model.pth
  module: segmentation_models_pytorch
  name: UnetPlusPlus
  args:
    in_channels: 14
    classes: 2

optimizer:
  restore_from: /content/drive/MyDrive/data_science_projects/landslide4sense-2022/models/misunderstood-sound-36/epoch_5_val_f1=72.615/optimizer.pt
  module: torch.optim
  name: Adam
  args:
    lr:  0.001
    weight_decay: 0.0005

loss:
  module: torch.nn
  name: CrossEntropyLoss
  args:
    ignore_index: 255

train:
  start_epoch: 11
  steps_per_epoch: 160
  batch_size: 100
  num_workers: 2
  num_steps: 10000
  num_steps_stop: 10000
  gpu_id: 0
  snapshot_dir: /content/drive/MyDrive/data_science_projects/landslide4sense-2022/predictions/misunderstood-sound-36-continuation/
  seed: 42
  callbacks:
    early_stopping:
      monitor: val_f1
      mode: max
      patience: 10
      best_result: 0.5
    wandb:
      group: Unet++
      tags:
        - val_split
        - spatial_data_aug
        - sgd_momentum
        - non_spatial_data_aug
