data:
  dir: ${hydra:runtime.cwd}/data/
  train_list: ${hydra:runtime.cwd}/data/train.txt
  eval_lists_paths:
    - ${hydra:runtime.cwd}/data/train.txt
  eval_names:
    - train
  test_list: ${hydra:runtime.cwd}/data/valid.txt
  input_size: [128, 128]
  augmentation:
    module: landslide4sense.data.augmentations
    name: transforms

model:
  restore_from: /content/drive/MyDrive/data_science_projects/landslide4sense-2022/models/quiet-salad-43/epoch_4_train_f1=73.748/model.pth
  module: segmentation_models_pytorch
  name: UnetPlusPlus
  args:
    in_channels: 14
    classes: 2

optimizer:
  restore_from:
  module: torch.optim
  name: Adam
  args:
    lr:  0.001
    weight_decay: 0.0005

loss:
  module: segmentation_models_pytorch.losses
  name: DiceLoss
  args:
    ignore_index: 255
    mode: multiclass

train:
  start_epoch: 0
  steps_per_epoch: 125
  batch_size: 128
  num_workers: 2
  num_steps: 10000
  num_steps_stop: 10000
  gpu_id: 0
  snapshot_dir: /content/drive/MyDrive/data_science_projects/landslide4sense-2022/models/
  seed: 42
  callbacks:
    early_stopping:
      monitor: train_f1
      mode: max
      patience: 10
      best_result: 0.5
    wandb:
      group: Unet++
      tags:
        - val_split
        - spatial_data_aug
        - sgd_momentum
        - non_spatial_data_aug

predict:
  snapshot_dir: /content/drive/MyDrive/data_science_projects/landslide4sense-2022/predictions/quiet-salad-43@0.5/
  threshold: 0.5