data:
  dir: ${hydra:runtime.cwd}/data/
  train_list: ${hydra:runtime.cwd}/data/train_cleaned.txt
  eval_lists_paths:
    - ${hydra:runtime.cwd}/data/train_cleaned.txt
  eval_names:
    - train
  test_list: ${hydra:runtime.cwd}/data/valid.txt
  input_size: [128, 128]
  augmentation:
    module: landslide4sense.data.augmentations
    name: transforms

model:
  restore_from: 
  module: segmentation_models_pytorch
  name: UnetPlusPlus
  args:
    in_channels: 14
    encoder_name: xception
    encoder_weights: imagenet
    classes: 2
    decoder_use_batchnorm: inplace # To reduce memory usage
    decoder_attention_type: scse # Attention

optimizer:
  restore_from:
  module: torch.optim
  name: Adam
  args:
    lr:  0.001
    weight_decay: 0.0005

loss:
  module: landslide4sense.losses
  name: Sum
  args:
    - module: landslide4sense.losses
      name: LogCoshTverskyLoss
      args:
        alpha: 0.7 # FP
        beta: 0.3 # FN
        ignore_index: 255
        mode: multiclass
    - module: segmentation_models_pytorch.losses
      name: FocalLoss
      args:
        alpha: 0.5 # Prior probability of having positive value in target.
        gamma: 0.2 # focal strength
        ignore_index: 255
        mode: multiclass

train:
  start_epoch: 0
  steps_per_epoch: 125
  batch_size: 128
  num_workers: 2
  num_steps: 10000
  num_steps_stop: 10000
  gpu_id: 0
  snapshot_dir: /content/drive/MyDrive/data_science_projects/landslide4sense-2022/models/
  seed: 42
  callbacks:
    early_stopping:
      monitor: train_f1
      mode: max
      patience: 10
      best_result: 0.5
    wandb:
      group: Unet++
      tags:
        - val_split
        - spatial_data_aug
        - sgd_momentum
        - non_spatial_data_aug

predict:
  snapshot_dir: /content/drive/MyDrive/data_science_projects/landslide4sense-2022/predictions/lyric-rain-44/
  threshold: 0.1